### ISSUE TITLE
App will not install on physical device

### ISSUE THREAD

**Issue by SimonSchwierzeck** [Nesteo/Nesteo-App#52]
Since the preperations for the google play store were done, the app is unable to install on physical devices, which had prior versions of the app installed.

**Comment by MarcusWichelmann** [comment]
That's normal behaviour as far as I know. I have this issue regulary and just uninstalling the previous version beforehand should resolve it.
This should only affect privous versions that have been installed from a different source (in this case, manually).
That's not your fault.

**Comment by SimonSchwierzeck** [comment]
Can be fixed by uninstalling the app using adb. 
adb uninstall "io.github.nesteo"
